# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170913_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.Student'),
        ),
    ]
